### PR TITLE
Merge user_login and user_profile to user_account

### LINKED ISSUE #41: Merge user_login and user_profile to 1 table

### PR DESCRIPTION
**Pull request by shah-tejas**
## Description

Merge user_login and user_profile to 1 table called user_account

## Issue

Fixes #41 

## Checklist
- [x] I have commented my code in hard-to-understand areas
- [x] I have created relevant Unit Tests for the feature I implemented
- [x] I have pulled and merged the latest code and resolved all merge conflicts
- [x] I have added someone to review this PR, and informed the team on Slack

### CODE REVIEW

**Review by dishanks9 — COMMENTED** [review]
Why they are merged? I might have missed the meeting when this was discussed

**Comment by shah-tejas** [comment]
> Why they are merged? I might have missed the meeting when this was discussed

Yes! These were 2 different tables only because we were planning to do Authentication by ourselves, using `user_login` table for that. However, since we are using Keycloak now, it is better to have just 1 User table.
Also, makes it easier w.r.t. frontend.

**Comment by shah-tejas** [comment]
Also @dishanks9 I think it is okay if you do not review the whole code, it is a huge change to review! I tested most of the APIs after this change, it seemed to work fine. Since there is not much development done yet, this should not affect much.

**Review by Nishit-Gopani — COMMENTED** [review]
Have some conflict (UserProfileService.java) need to resolve it, can you please look into it?

**Review by Nishit-Gopani — DISMISSED** [review]

**Review by Nishit-Gopani — APPROVED** [review]
Looks Good

**Pull request merged**
